# Generated by Django 5.0.1 on 2024-01-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.TextField(max_length=10),
        ),
    ]
