# Generated by Django 5.0.1 on 2024-01-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_task_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='desc',
        ),
    ]
